# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a58cca2b830c726674da171264e59ef3f4fdc8c1d6d60feb09fa17d28b9337507df99340f0579d5a1f775cd2deed749cda07dd3e38e029665d3ab6c899478e03

test:
  secret_key_base: d8e82f3535e9b9795fdd559bf3d24ff20384188962e155b84656422b8b723b531bc1fba049cb4c8fe4300c61781db3466ba68a476278f7049dcf8c0c36ef8c26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
